<?php

use App\Helpers\Pagination;
use App\Helpers\View;

$pagination = Pagination::make($this);

?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Usuários Cadastrados</h3>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                <a href="<?= $this->view->controller; ?>novo/" class="btn btn-info">
                    <i class="fa fa-asterisk"></i> Novo Registro
                </a>
                <?php endif ?>
                <div class="row">
                    <div class="col-md-7">
                        <?= $pagination; ?>
                    </div>
                    <div class="col-lg-5">
                        <form action="#" class="search-form" onsubmit="return false">
                            <div class="input-group search-input-box">
                                <input type="text" class="form-control search-input" placeholder="Nome ou OM">
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary search-button" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>OM</th>
                            <th>Nível</th>
                            <th>Ativo</th>
                            <th>Criado</th>
                            <th>Alterado</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value) : ?>
                            <tr>
                                <td><?= $value['id']; ?></td>
                                <td><?= $value['name']; ?></td>
                                <td><?= $value['naval_indicative']; ?></td>
                                <td><?= $value['level']; ?></td>
                                <td>
                                    <span class='label label-<?= $value['isActive'] == 1 ? 'success' : 'danger'; ?>'>
                                        <?= $value['isActive'] == 1 ? 'Sim' : 'Não'; ?>
                                    </span>
                                </td>
                                <td><?= View::humanDate($value['created_at']); ?></td>
                                <td><?= View::humanDate($value['updated_at']); ?></td>
                                <td>
                                    <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                                    <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success">
                                        <i class="fa fa-edit"></i> Editar
                                    </a>
                                    <a onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>')" class="btn btn-danger">
                                        <i class="fa fa-trash"></i> Eliminar
                                    </a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <?= $pagination; ?>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
<script>
    $('.search-button').click(function() {
        btnSearch();
    });
    $('.search-input').keypress(function(event){
        var keycode = (event.keyCode ? event.keyCode : event.which);
        if(keycode == '13') {
            btnSearch();
        }
    });
    function btnSearch() {
        var searchInput = $('.search-input');
        var searchValue = searchInput.val();
        var url = 'acesso/visualizar/';
        if (searchValue && url) {
            window.location = url + 'busca/' + searchValue;
        } else {
            searchInput.focus();
        }
    }
</script>