<?php

use App\Helpers\View;
use App\Helpers\Utils;

?>
<style>
    .autocomplete {
        position: relative;
    }

    .autocomplete-items {
        position: absolute;
        border: 1px solid #d4d4d4;
        border-bottom: none;
        border-top: none;
        z-index: 99;
        top: 100%;
        left: 0;
        right: 0;
    }

    .autocomplete-items div {
        padding: 10px;
        cursor: pointer;
        background-color: #fff; 
        border-bottom: 1px solid #d4d4d4; 
    }

    .autocomplete-items div:hover {
        background-color: #e9e9e9; 
    }

    .autocomplete-active {
        background-color: DodgerBlue !important; 
        color: #ffffff; 
    }

</style>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>
        <form action="<?= $this->view->controller; ?>acompanhamento/" method="post" id="form">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-cogs fa-fw"></i> Cadastro de Documento (Acompanhamento)
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="resultado"></div>
                            <div class="row">
                                <div class="col-lg-6">

                                    <div class="form-group">
                                        <label>UASG</label>
                                        <select name="uasg_id" id="uasg_id" class="form-control" required>
                                            <option value="">Selecione a UASG</option>
                                            <?php foreach ($this->view->resultOm as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['naval_indicative']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>NUP</label>
                                        <input type="text" id="nup" name="nup" placeholder="NUP" class="form-control" maxlength="30" autocomplete="off" required>
                                    </div>

                                    <div class="form-group">
                                        <label>Objeto</label>
                                        <input type="text" id="objeto" name="objeto" placeholder="Objeto" class="form-control" maxlength="200" autocomplete="off" required>
                                    </div>

                                    <div class="form-group">
                                        <label>Observações</label>
                                        <input type="text"
                                            name="observation"
                                            id="observation"
                                            placeholder="Observações"
                                            class="form-control"/>
                                    </div>

                                    <div class="form-group">
                                        <label>Data/Hora de inclusão/alteração do documento</label>
                                        <input type="text" id="created_at" name="created_at" class="form-control" data-mask="00-00-0000 00:00:00" data-mask-reverse="true" value="<?= date('d-m-Y h:i:s') ?>">
                                    </div>
                                </div>

                                <div class="col-lg-6">

                                    <div class="form-group">
                                        <label>Modalidade</label>
                                        <select name="modality_id" id="modality_id" class="form-control" required>
                                            <option value="">Selecione a modalidade</option>
                                            <option value="1"> Dispensa Eletrônica </option>
                                            <option value="2"> Pregão Eletrônico </option>
                                            <option value="3"> Concorrência </option>
                                            <option value="4"> Adesão </option>
                                            <option value="5"> TJDL </option>
                                            <option value="6"> TJIL </option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Número</label>
                                        <input type="text" id="number" name="number" placeholder="Número do documento" class="form-control" maxlength="30" autocomplete="off" required>
                                    </div>

                                    <div class="form-group">
                                        <label>Valor estimado do documento (R$)</label>
                                        <input type="text"
                                            id="valor_estimado"
                                            name="valor_estimado"
                                            placeholder="Valor em Reais"
                                            class="form-control"
                                            required>
                                    </div>

                                    <div class="form-group">
                                        <label>Status</label>
                                        <select name="status_id" id="status_id" class="form-control" required>
                                            <option value="">Selecione o Status</option>
                                            <?php foreach ($this->view->resultStatus as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['description']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <button class="btn btn-success"><i class="fa fa-check"></i> Registrar</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
        </form>
        <!-- /.container-fluid -->
    </div>
</div>