<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Cadastro de Documento (Acompanhamento)
                    </div>
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>registra/" method="post" id="form">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                    <label>NUP</label>
                                    <input type="text"
                                           id="nup"
                                           name="nup" 
                                           placeholder="NUP"
                                           class="form-control"
                                           required>
                                    </div>
                                    <div class="form-group">
                                        <label>Modalidade</label>
                                        <input type="text"
                                               id="modality_id"
                                               name="modality_id"
                                               placeholder="Modality"
                                               class="form-control"
                                               required>
                                    </div>
                                    <div class="form-group">
                                        <label>Número</label>
                                        <input type="text"
                                               id="number"
                                               name="number"
                                               placeholder="Número"
                                               class="form-control"
                                               required>
                                    </div>
                                    <div class="form-group">
                                        <label>UASG</label>
                                        <input type="text"
                                               id="uasg_id"
                                               name="uasg_id"
                                               placeholder="UASG"
                                               class="form-control"
                                               required>
                                    </div>
                                    <div class="form-group">
                                        <label>Objeto</label>
                                        <input type="text"
                                               id="objeto"
                                               name="objeto"
                                               placeholder="Objeto"
                                               class="form-control"
                                               required>
                                    </div>
                                    <div class="form-group">
                                        <label>Valor Estimado</label>
                                        <input type="text"
                                               id="valor_estimado"
                                               name="valor_estimado"
                                               placeholder="Valor Estimado"
                                               class="form-control"
                                               required>
                                    </div>
                                    <div class="form-group">
                                        <label>Status</label>
                                        <input type="text"
                                               id="status_id"
                                               name="status_id"
                                               placeholder="Status"
                                               class="form-control"
                                               required>
                                    </div>
                                    <div class="form-group">
                                        <label>Observação</label>
                                        <input type="text"
                                               id="observation"
                                               name="observation"
                                               placeholder="Observação"
                                               class="form-control"
                                               required>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <br>
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Registrar</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>