<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Lista de Documentos Protocolados (Acompanhamento)</h3>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <a href="<?=$this->view->controller;?>" class="btn btn-warning pull-right"><i class="fa fa-arrow-left"></i> Voltar</a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>NUP</th>
                            <th>Modalidade</th>
                            <th>Valor estimado (R$)</th>
                            <th>UASG</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value) : ?>
                            <tr>
                                <td><?= $value['nup']; ?></td>
                                <td><?= $value['modality_id']; ?></td>
                                <td><?= 'R$ ' . number_format($value['valor_estimado'], 2, ',', '.'); ?></td>
                                <td><?= $value['uasg_id']; ?></td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $value['id']; ?>" class="btn btn-primary">
                                        <i class="fa fa-eye"></i> Detalhar
                                    </a>
                                    <a href="<?= $this->view->controller; ?>historico/id/<?= $value['id']; ?>" class="btn btn-success">
                                        <i class="fa fa-eye"></i> Histórico do Documento
                                    </a>
                                    <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                                    <a href="<?= $this->view->controller; ?>status/id/<?= $value['id']; ?>" class="btn btn-info">
                                        <i class="fa fa-plus-square"></i> Adicionar Status
                                    </a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?= $this->view->controller; ?>protocolado_acompanhamento/om/<?= $this->view->result[0]['om']; ?>/pagina/<?= $this->view->btn['previus']; ?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value) : ?>
                            <li><a href="<?= $this->view->controller; ?>protocolado_acompanhamento/om/<?= $this->view->result[0]['om']; ?>/pagina/<?= $value; ?>"><?= $value; ?></a></li>
                        <?php endforeach; ?>
                        <li>
                            <a href="<?= $this->view->controller; ?>protocolado_acompanhamento/om/<?= $this->view->result[0]['om']; ?>/pagina/<?= $this->view->btn['next']; ?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->