<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Lista de Documentos Protocolados (Acompanhamento)</h3>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <a href="<?=$this->view->controller;?>" class="btn btn-warning pull-right"><i class="fa fa-arrow-left"></i> Voltar</a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>NUP</th>
                            <th>Modalidade</th>
                            <th>UASG</th>
                            <th>Número</th>
                            <th>Objeto</th>
                            <th>Valor estimado (R$)</th>
                            <th>Data/hora alteração (R$)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value) : ?>
                            <tr>
                                <td><?= $value['nup']; ?></td>
                                <td><?= $value['modality']; ?></td>
                                <td><?= $value['naval_indicative']; ?></td>
                                <td><?= $value['document_number']; ?></td>
                                <td><?= $value['summary_object']; ?></td>
                                <td><?= 'R$ ' . number_format($value['document_value'], 2, ',', '.'); ?></td>
                                <td><?= $value['updated_at']; ?></td>  

                                <td>
                                    <a href="<?= $this->view->controller; ?>historico/id/<?= $value['id']; ?>" class="btn btn-success">
                                        <i class="fa fa-eye"></i> Histórico do Documento
                                    </a>
                                    <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                                    <a href="<?= $this->view->controller; ?>status/id/<?= $value['id']; ?>" class="btn btn-info">
                                        <i class="fa fa-plus-square"></i> Adicionar Status
                                    </a>
                                    <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <?php endif ?>                                  

                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?= $this->view->controller; ?>protocolado/om/<?= $this->view->result[0]['om']; ?>/pagina/<?= $this->view->btn['previus']; ?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value) : ?>
                            <li><a href="<?= $this->view->controller; ?>protocolado/om/<?= $this->view->result[0]['om']; ?>/pagina/<?= $value; ?>"><?= $value; ?></a></li>
                        <?php endforeach; ?>
                        <li>
                            <a href="<?= $this->view->controller; ?>protocolado/om/<?= $this->view->result[0]['om']; ?>/pagina/<?= $this->view->btn['next']; ?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->