<?php

use App\Helpers\View;

?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <form action="<?= $this->view->controller; ?>registra/" method="post" id="form">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-cogs fa-fw"></i> Configuração inicial
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="resultado"></div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>OMAp</label>
                                        <select onchange="valorComprometido()" name="om" id="om" class="form-control" required>
                                            <?php foreach ($this->view->resultOm as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['naval_indicative']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Modalidade</label>
                                        <select onchange="valorComprometido()" name="modality" id="modality" class="form-control" required>
                                            <option value="1"> Dispensa de Licitação </option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Enquadramento</label>
                                        <select onchange="valorComprometido()" name="enquadramento" id="enquadramento" class="form-control" required>
                                            <?php foreach ($this->view->credito as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['credit_note']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>CNAE</label>
                                        <input type="text"
                                               id="cnae"
                                               name="cnae"
                                               placeholder="CNAE da Empresa (se for mais de um separe por vírgula)"
                                               class="form-control"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Empresa</label>
                                        <select name="supplier" id="supplier" class="form-control supplier" required>
                                            <?php foreach ($this->view->resultFornecedor as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['name']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Natureza da Despesa</label>
                                        <select onchange="valorComprometido()" name="natureExpense" id="natureExpense" class="form-control" required>
                                            <?php foreach ($this->view->resultNatureExpense as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['name']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>SubItem</label>
                                        <select onchange="valorComprometido()" name="subItem" id="subItem" class="form-control" required>
                                            <?php for ($i = 1; $i <= 100; $i++) : ?>
                                                <option value="<?= $i; ?>">
                                                    <?= $i; ?>
                                                </option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Artigo</label>
                                        <select name="article" id="article" class="form-control" required>
                                            <option value="24">24</option>
                                            <option value="75">75</option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Incisivo</label>
                                        <select name="incisive" id="incisive" class="form-control" required>
                                            <option value="1">I</option>
                                            <option value="2">II</option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>CNPJ/CPF</label>
                                        <input type="text"
                                               id="cpfcnpj"
                                               name="cnpj"
                                               placeholder="CNPJ ou CPF do Fornecedor"
                                               class="form-control"
                                               maxlength="18"
                                               onchange="cpfCnpj()"
                                               required>
                                        <p class="help-block">Ex.: 00.000.000/0001-00 ou 000.000.000-00</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Número do Documento</label>
                                        <input type="text" id="document_number" name="document_number" placeholder="Número do Documento" class="form-control" maxlength="10" autocomplete="off" required>
                                    </div>
                                </div>

                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Valor do Documento (R$)</label>
                                        <input type="text" id="document_value" name="document_value" placeholder="Valor em Reais" class="form-control" data-mask="000.000.000,00" data-mask-reverse="true" maxlength="14" autocomplete="off" required>
                                    </div>
                                </div>

                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Status</label>
                                        <select name="status" id="status" class="form-control" required>
                                            <?php foreach ($this->view->resultStatus as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['name']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Valor Disponível</label>
                                        <input type="text" class="form-control" id="saldoDisponivel" disabled>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Valor comprometido</label>
                                        <input type="text" id="saldoComprometido" class="form-control" disabled>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Data/Hora</label>
                                        <input type="text" id="datetime" name="datetime" class="form-control" data-mask="00-00-0000 00:00:00" data-mask-reverse="true" value="<?= date('d-m-Y h:i:s') ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <button class="btn btn-success"><i class="fa fa-check"></i> Registrar</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
        </form>
        <!-- /.container-fluid -->
    </div>
</div>
<!-- /#page-wrapper -->
<script>
    function valorComprometido() {
        var enquadramento = $('#enquadramento').val();

        var om = $('#om').val();
        var subItem = $('#subItem').val();
        var empresa = $('#supplier').val();
        var incisivo = $('#incisive').val();
        var modalidade = $('#modality').val();
        var naturezaDespesa = $('#natureExpense').val();

        $.ajax({
            type: "GET",
            url: `http://localhost/app/protocolo/credito/findSaldoComprometido` +
                `/om/${om}/subItem/${subItem}/supplier/${empresa}` +
                `/incisive/${incisivo}/modality/${modalidade}` +
                `/enquadramento/${enquadramento}/natureExpense/${naturezaDespesa}`,
            dataType: 'json',
        }).done(function(res) {
            let credito = res.credit_value ?? 0;
            let saldo = res.registers_value ?? 0;
            $("#saldoDisponivel").val('R$ ' + credito.toLocaleString('pt-BR', {minimumFractionDigits: 2}));
            $("#saldoComprometido").val('R$ ' + saldo.toLocaleString('pt-BR', {minimumFractionDigits: 2}));
        });
    }

    $(document).ready(function() {
        $("select.supplier").change(function() {
            var id = $(this).children("option:selected").val();
            $.ajax({
                type: "GET",
                url: `http://localhost/app/protocolo/fornecedor/findById/id/${id}`,
                dataType: 'json',
            }).done(function(res) {
                $("#cpfcnpj").val(res.cnpj);
                console.log(res);
            });
        });
    });
</script>