<?php

use App\Helpers\View;

?>
<style>
    .autocomplete {
        position: relative;
    }

    .autocomplete-items {
        position: absolute;
        border: 1px solid #d4d4d4;
        border-bottom: none;
        border-top: none;
        z-index: 99;
        top: 100%;
        left: 0;
        right: 0;
    }

    .autocomplete-items div {
        padding: 10px;
        cursor: pointer;
        background-color: #fff; 
        border-bottom: 1px solid #d4d4d4; 
    }

    .autocomplete-items div:hover {
        background-color: #e9e9e9; 
    }

    .autocomplete-active {
        background-color: DodgerBlue !important; 
        color: #ffffff; 
    }

</style>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <form action="<?= $this->view->controller; ?>registra/" method="post" id="form">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-cogs fa-fw"></i> Configuração inicial
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="resultado"></div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>OMAp</label>
                                        <select name="om" id="om" class="form-control" required>
                                            <option value="">Selecione a OM</option>
                                            <?php foreach ($this->view->resultOm as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['naval_indicative']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Modalidade</label>
                                        <select name="modality" id="modality" class="form-control" required>
                                            <option value="1"> Dispensa de Licitação </option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Enquadramento</label>
                                        <select onchange="valorComprometido()" name="enquadramento" id="enquadramento" class="form-control" required>
                                            <?php foreach ($this->view->credito as $key => $value) : ?>
                                                <option value="<?= $value['id'] ?>" <?= $value['id'] == 2 ? 'selected' : '' ?>>
                                                    <?= $value['credit_note']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>CNAE</label>
                                        <div class="autocomplete">
                                            <input type="hidden" id="cnae_value" name="cnae">
                                            <input type="text" id="cnae" class="form-control" onchange="valorComprometido()" placeholder="Informe um CNAE da Empresa" required>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Natureza da Despesa</label>
                                        <select name="nature_expense" id="nature_expense" class="form-control" required>
                                            <?php foreach ($this->view->resultNatureExpense as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['name']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>SubItem</label>
                                        <select name="sub_item" id="sub_item" class="form-control" required>
                                            <option> Selecione um SubItem </option>
                                            <?php for ($i = 1; $i <= 99; $i++) : ?>
                                                <option value="<?= $i; ?>">
                                                    <?= $i; ?>
                                                </option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Artigo</label>
                                        <select name="article" id="article" class="form-control" required>
                                            <option value="24">24</option>
                                            <option value="75" selected>75</option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Inciso</label>
                                        <select name="incisive" id="incisive" class="form-control" required>
                                            <option value="1">I</option>
                                            <option value="2" selected>II</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Empresa</label>
                                        <select name="supplier" id="supplier" class="form-control supplier" required>
                                            <option value="">Selecione uma empresa</option>
                                            <?php foreach ($this->view->resultFornecedor as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['name']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Número do Documento</label>
                                        <input type="text" id="document_number" name="document_number" placeholder="Número do Documento" class="form-control" maxlength="10" autocomplete="off" required>
                                    </div>
                                </div>

                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>CNPJ/CPF</label>
                                        <input type="text"
                                               id="cpfcnpj"
                                               name="cnpj"
                                               placeholder="CNPJ ou CPF do Fornecedor"
                                               class="form-control"
                                               maxlength="18"
                                               onchange="cpfCnpj()"
                                               required>
                                    </div>
                                    <div class="form-group">
                                        <label>Valor do Documento (R$)</label>
                                        <input type="text" id="document_value" name="document_value" placeholder="Valor em Reais" class="form-control" data-mask="000.000.000,00" data-mask-reverse="true" maxlength="14" autocomplete="off" required>
                                    </div>
                                </div>

                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Observações</label>
                                        <input type="text"
                                            name="observation"
                                            id="observation"
                                            placeholder="Observações"
                                            class="form-control"/>
                                    </div>

                                    <div class="form-group">
                                        <label>Status</label>
                                        <select name="status" id="status" class="form-control" required>
                                            <?php foreach ($this->view->resultStatus as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['name']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Valor Disponível</label>
                                        <input type="text" class="form-control" id="saldoDisponivel" disabled>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Valor comprometido</label>
                                        <input type="text" id="saldoComprometido" class="form-control" disabled>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Data/Hora</label>
                                        <input type="text" id="datetime" name="datetime" class="form-control" data-mask="00-00-0000 00:00:00" data-mask-reverse="true" value="<?= date('d-m-Y h:i:s') ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <button class="btn btn-success"><i class="fa fa-check"></i> Registrar</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
        </form>
        <!-- /.container-fluid -->
    </div>
</div>
<!-- /#page-wrapper -->
<script>
    function valorComprometido() {
        var enquadramento = $('#enquadramento').val();
        var om = $('#om').val();
        var cnae = $('#cnae_value').val();

        $.ajax({
            type: "GET",
            url: `/app/protocolo/credito/findSaldoComprometido` +
                `/om/${om}/enquadramento/${enquadramento}/cnae/${cnae}`,
            dataType: 'json',
        }).done(function(res) {
            let credito = res.credit_value ?? 0;
            let saldo = res.registers_value ?? 0;
            $("#saldoDisponivel").val('R$ ' + credito.toLocaleString('pt-BR', {minimumFractionDigits: 2}));
            $("#saldoComprometido").val('R$ ' + saldo.toLocaleString('pt-BR', {minimumFractionDigits: 2}));
        });
    }

    $(document).ready(function() {
        $("select.supplier").change(function() {
            var id = $(this).children("option:selected").val();
            $.ajax({
                type: "GET",
                url: `/app/protocolo/fornecedor/findById/id/${id}`,
                dataType: 'json',
            }).done(function(res) {
                $("#cpfcnpj").val(res.cnpj);
                console.log(res);
            });
        });
    });
</script>