<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Cadastro
                    </div>
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>registra/" method="post" id="form">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Nota de crédito</label>
                                        <input type="text"
                                               id="credit_note"
                                               name="credit_note"
                                               placeholder="Nota de crédito"
                                               class="form-control"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Valor</label>
                                        <input type="text"
                                               name="value"
                                               id="value"
                                               data-mask="000.000.000,00"
                                               data-mask-reverse="true"
                                               placeholder="Valor da nota de crédito"
                                               class="form-control"
                                               maxlength="10"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <br>
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Registrar</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>