<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Edição
                    </div>
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>altera/" method="post" id="form">
                            <input type="hidden" name="id" value="<?= $this->view->result['id']; ?>">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text"
                                               id="name"
                                               name="name"
                                               placeholder="Nome da Empresa"
                                               class="form-control"
                                               value="<?= $this->view->result['name']; ?>"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>CNPJ/CPF</label>
                                        <input type="text"
                                               id="cpfcnpj"
                                               name="cnpj"
                                               placeholder="CNPJ ou CPF do Fornecedor"
                                               class="form-control"
                                               maxlength="18"
                                               onkeypress="cpfCnpj()"
                                               value="<?= $this->view->result['cnpj']; ?>"
                                               required>
                                        <p class="help-block">Ex.: 00.000.000/0001-00 ou 000.000.000-00</p>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Telefone de contato</label>
                                        <textarea
                                            name="telcontato"
                                            id="telcontato"
                                            placeholder="Telefone de contato da empresa"
                                            class="form-control"
                                            required><?= $this->view->result['telcontato']; ?></textarea>
                                        <p class="help-block">Telefone de contato</p>
                                    </div>

                                    <div class="form-group">
                                        <label>E-mail</label>
                                        <textarea
                                            name="email"
                                            id="email"
                                            placeholder="E-mail da empresa"
                                            class="form-control"
                                            required><?= $this->view->result['email']; ?></textarea>
                                        <p class="help-block">E-mail da empresa</p>
                                    </div>

                                    <div class="form-group">
                                        <label>Endereço</label>
                                        <textarea
                                            name="endereco"
                                            id="endereco"
                                            placeholder="Endereço da empresa"
                                            class="form-control"
                                            required><?= $this->view->result['endereco']; ?></textarea>
                                        <p class="help-block">Endereço da empresa</p>
                                    </div>

                                    <div class="form-group">
                                        <br>
                                        <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Alterar</button>
                                        <?php endif; ?>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>