<?php

use App\Helpers\View;
use App\Helpers\Utils;

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Cadastro
                    </div>
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>remaneja/idlista/<?= $this->view->idlista; ?>" method="post" id="form">
                            <input type="hidden" name="id" value="<?= $this->view->result['id']; ?>">
                            <input type="hidden" name="number" value="<?= $this->view->result['number']; ?>">
                            <input type="hidden" name="suppliers_id" value="<?= $this->view->result['suppliers_id']; ?>">
                            <input type="hidden" name="biddings_id" value="<?= $this->view->idlista; ?>">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text"
                                               name="name"
                                               id="name"
                                               placeholder="Nome do Item da Licitação"
                                               class="form-control"
                                               value="<?= $this->view->result['name']; ?>"
                                               disabled>
                                    </div>

                                    <div class="form-group">
                                        <label>Quantidade disponível</label>
                                        <input type="text"
                                               name="quantity"
                                               id="quantity"
                                               placeholder="Quantidade Licitada"
                                               class="form-control"
                                               maxlength="50"
                                               value="<?= intval($this->view->result['quantity']); ?>"
                                               disabled>
                                    </div>

                                    <div class="form-group">
                                        <label>OMAp de Origem</label>
                                        <select class="form-control" disabled>
                                            <?php foreach ($this->view->resultOms as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>" 
                                                <?= ($this->view->result['oms_id'] == $value['id']) ? 'selected' : '' ?>>
                                                    <?= $value['naval_indicative']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Licitação de destino</label>
                                        <select name="bidding_destiny" id="bidding_destiny" class="form-control" required>
                                            <?php foreach ($this->view->resultLicitacao as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['number'] . ' - '. $value['description']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Quantidade para remanejar</label>
                                        <input type="text"
                                               name="quantity_relocate"
                                               id="quantity_relocate"
                                               placeholder="Quantidade para remanejar"
                                               class="form-control"
                                               maxlength="50">
                                    </div>

                                    <div class="form-group">
                                        <label>OMAp de destino</label>
                                        <select name="om_destiny" id="om_destiny" class="form-control" required>
                                            <?php foreach ($this->view->resultOms as $key => $value) : ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['naval_indicative']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <button class="btn btn-primary">
                                            <i class="fa fa-exchange"></i> Remanejar
                                        </button>
                                        <a href="<?= $this->view->controller; ?>listar/idlista/<?= $this->view->idlista; ?>" class="btn btn-warning">
                                            <i class="fa fa-arrow-left"></i> Voltar
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>