<?php

use App\Helpers\View;
use App\Helpers\Utils;

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>
        <form action="<?= $this->view->controller; ?>altera/idlista/<?= $this->view->idlista; ?>" method="post" id="form">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-table fa-fw"></i> Formulário de Cadastro
                        </div>
                        <div class="panel-body">
                            <div id="resultado"></div>
                            <input type="hidden" name="id" value="<?= $this->view->result['id']; ?>">
                            <input type="hidden" name="biddings_id" value="<?= $this->view->idlista; ?>">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Número</label>
                                        <input type="text"
                                                name="number"
                                                id="number"
                                                placeholder="Número do Item"
                                                class="form-control"
                                                value="<?= $this->view->result['number']; ?>"
                                                required>
                                    </div>

                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text"
                                                name="name"
                                                id="name"
                                                placeholder="Nome do Item da Licitação"
                                                class="form-control"
                                                value="<?= $this->view->result['name']; ?>"
                                                required>
                                    </div>

                                    <div class="form-group">
                                        <label>Fornecedor</label>
                                        <select name="suppliers_id" class="form-control" required>
                                            <?php foreach ($this->view->resultFornecedor as $value): ?>
                                                <option value="<?= $value['id']; ?>" <?= View::isSelected($this->view->result['suppliers_id'], $value['id']); ?>>
                                                    <?= $value['name']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>UF</label>
                                        <input type="text"
                                                name="uf"
                                                id="uf"
                                                placeholder="Unidade de Fornecimento do Item"
                                                class="form-control"
                                                maxlength="4"
                                                value="<?= $this->view->result['uf']; ?>"
                                                required>
                                    </div>

                                    <div class="form-group">
                                        <label>Valor</label>
                                        <input type="text"
                                                name="value"
                                                id="value"
                                                placeholder="Valor do item"
                                                class="form-control"
                                                maxlength="12"
                                                value="<?= Utils::floatToMoney($this->view->result['value'], ''); ?>"
                                                required>
                                    </div>

                                    <div class="form-group">
                                        <label>Habilitar Item para pedidos?</label>
                                        <input type="checkbox"
                                                name="active"
                                                id="active"
                                                <?= $this->view->result['active'] == 'yes' ? 'checked' : ''; ?>>
                                        <span class='label label-danger'>SIM!</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-table fa-fw"></i> OMs Registradas para este item
                            <a href="<?= $this->view->controller; ?>adicionarom/id/<?= $this->view->result['id']; ?>/idlista/<?= $this->view->idlista; ?>"
                            class="btn btn-info pull-right"
                            style="margin-top: -7px;">
                                <i class="fa fa-plus-circle"></i> Adicionar OM
                            </a>
                        </div>
                        <div class="panel-body">
                            <div class="row" style="margin-top: 10px;">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Indicativo Naval</th>
                                            <th>Nome</th>
                                            <th>Qtd Licitada</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->view->resultOms as $value): ?>
                                            <tr>
                                                <td><?= $value['naval_indicative'] ?? ''; ?></td>
                                                <td><?= $value['name'] ?? ''; ?></td>
                                                <td>
                                                    <input type="hidden" name="ids[]" value="<?= $value['id']; ?>">
                                                    <input
                                                        type="text"
                                                        name="quantity[]"
                                                        id="quantity"
                                                        class="form-control"
                                                        value="<?= $value['quantity']; ?>">
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary">
                            <i class="fa fa-check"></i> Alterar
                        </button>
                        <a href="<?= $this->view->controller; ?>listar/idlista/<?= $this->view->idlista; ?>" class="btn btn-warning">
                            <i class="fa fa-arrow-left"></i> Voltar
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>