<?php

use App\Helpers\Pagination;
use App\Helpers\View;
use App\Helpers\Utils;

$idlista = $this->view->idlista;

$pagination = Pagination::make($this, function ($btn, $controllerName) use ($idlista) {
    return [
        'previous' => "{$controllerName}listar/idlista/{$idlista}/pagina/{$btn['previous']}",
        'next' => "{$controllerName}listar/idlista/{$idlista}/pagina/{$btn['next']}",
        'current' => "{$controllerName}listar/idlista/{$idlista}/pagina/" . Pagination::CURRENT_PAGE
    ];
});

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Itens do Processo Licitatório</h3>
                <div class="alert alert-info" role="alert">
                    Número: <strong><?= $this->view->resultLicitacao['number']; ?></strong><br>
                    Órgão:
                    <strong>
                        <?= $this->view->resultLicitacao['uasg']; ?>
                        -
                        <?= $this->view->resultLicitacao['uasg_name']; ?>
                    </strong>
                </div>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <?php if (in_array($this->view->userLoggedIn['level'], [1, 2])) : ?>
                    <a href="<?= $this->view->controller; ?>novo/idlista/<?= $this->view->idlista; ?>" class="btn btn-info">
                        <i class="fa fa-plus-circle"></i> Novo Registro
                    </a>
                <?php endif ?>
                <a href="<?= $this->view->controller; ?>" class="btn btn-warning pull-right">
                    <i class="fa fa-arrow-left"></i> Voltar
                </a>
                <div class="row">
                    <div class="col-md-6">
                        <?= $pagination; ?>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Qtd Licitada</th>
                            <th>Qtd Disponível</th>
                            <th>Valor</th>
                            <th>UF</th>
                            <th>Descrição item</th>
                            <th>PDM</th>
                            <th>CATMAT/CATSER</th>
                            <th>Fornecedor</th>
                            <th>Habilitado</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value) : ?>
                            <tr>
                                <td style='font-size: 11px'><?= $value['number']; ?></td>
                                <td style='font-size: 11px'><?= Utils::normalizeFloat($value['quantity']); ?></td>
                                <td style='font-size: 11px'><?= Utils::normalizeFloat($value['quantity_available']); ?></td>
                                <td style='font-size: 11px'><?= Utils::floatToMoney($value['value']); ?></td>
                                <td style='font-size: 11px'><?= $value['uf']; ?></td>
                                <td style='font-size: 11px'><?= $value['name']; ?></td>
                                <td style='font-size: 11px'><?= $value['codpdm_items']; ?></td>
                                <td style='font-size: 11px'><?= $value['coditem_items']; ?></td>
                                <td style='font-size: 11px'>
                                    <?= View::limitString($value['supplier'], 25); ?>
                                </td>
                                <td style='font-size: 11px'>
                                    <span class='label label-<?= $value['active'] === 'yes' ? 'success' : 'danger'; ?>'>
                                        <?= $value['active'] === 'yes' ? 'Sim' : 'Não'; ?>
                                    </span>
                                </td>
                                <td>
                                    <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                                        <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>/idlista/<?= $this->view->idlista; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>/idlista/<?= $this->view->idlista; ?>')" class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>