<?php

use App\Helpers\View;
use App\Helpers\Utils;

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Relatório de ...</h3>
                <i class="fa fa-filter"></i> Filtros
                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>OMAp</label>
                            <select class="form-control" name="om" id="om">
                                <?php foreach ($this->view->resultOms as $value) : ?>
                                    <option value="<?= $value['id'] ?>" <?= $value['id'] == $this->getParam('om') ? 'selected' : '' ?>>
                                        <?= $value['naval_indicative'] ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>Modalidade</label>
                            <select name="modality" id="modality" class="form-control" required>
                                <option value="1"> Dispensa de Licitação </option>
                                <option value="2"> Pregão Eletrônico </option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>Enquadramento</label>
                            <select name="enquadramento" id="enquadramento" class="form-control" required>
                                <?php foreach ($this->view->credito as $key => $value) : ?>
                                    <option value="<?= $value['id']; ?>" <?= $value['id'] == $this->getParam('modality') ? 'selected' : '' ?>>
                                        <?= $value['credit_note']; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>Empresa</label>
                            <select name="supplier" id="supplier" class="form-control supplier" required>
                                <option value="">Selecione uma empresa</option>
                                <?php foreach ($this->view->resultFornecedor as $key => $value) : ?>
                                    <option value="<?= $value['id']; ?>" <?= $value['id'] == $this->getParam('supplier') ? 'selected' : '' ?>>
                                        <?= $value['name']; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>Natureza da Despesa</label>
                            <select name="natureExpense" id="natureExpense" class="form-control" required>
                                <?php foreach ($this->view->resultNatureExpense as $key => $value) : ?>
                                    <option value="<?= $value['id']; ?>" <?= $value['id'] == $this->getParam('natureExpense') ? 'selected' : '' ?>>
                                        <?= $value['name']; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>SubItem</label>
                            <select name="subItem" id="subItem" class="form-control" required>
                                <?php for ($i = 1; $i <= 100; $i++) : ?>
                                    <option value="<?= $i; ?>" <?= $value['id'] == $this->getParam('subItem') ? 'selected' : '' ?>>
                                        <?= $i; ?>
                                    </option>
                                <?php endfor; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>Artigo</label>
                            <select name="article" id="article" class="form-control" required>
                                <option value="24">24</option>
                                <option value="75">75</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label>Inciso</label>
                            <select name="incisive" id="incisive" class="form-control" required>
                                <option value="1">I</option>
                                <option value="2" selected>II</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-1" style="margin-top: 25px;">
                        <button class="btn btn-info btn-apply-search">
                            <i class="fa fa-search"></i>
                        </button>

                        <button class="btn btn-danger btn-apply-clean">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>OM</th>
                            <th>Número</th>
                            <th>Valor</th>
                            <th>Saldo Comprometido</th>
                            <th>Saldo Disponível</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value) : ?>
                            <tr>
                                <td><?= $value['naval_indicative']; ?></td>
                                <td><?= $value['document_number']; ?></td>
                                <td><?= Utils::floatToMoney($value['document_value']); ?></td>
                                <td><?= Utils::floatToMoney($value['registers_value']); ?></td>
                                <td><?= Utils::floatToMoney($value['credit_value']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        var btnApplySearch = $('.btn-apply-search');
        var btnApplyClear = $('.btn-apply-clean');

        btnApplyClear.click(function() {
            window.location = 'relatorio/controle/';
        });

        btnApplySearch.click(function() {
            btnSearch();
        });

        function btnSearch() {
            var selectOm = $('#om').val();
            var subItem = $('#subItem').val();
            var empresa = $('#supplier').val();
            var enquadramento = $('#enquadramento').val();
            var incisivo = $('#incisive').val();
            var modalidade = $('#modality').val();
            var naturezaDespesa = $('#natureExpense').val();
            var url = 'relatorio/controle/';

            if (!selectOm && !subItem && !empresa && !incisivo && !modalidade) {
                return;
            }

            if (selectOm) {
                url += 'om/' + selectOm + '/';
            }
            if (enquadramento) {
                url += 'enquadramento/' + enquadramento + '/';
            }
            if (subItem) {
                url += 'subItem/' + subItem + '/';
            }
            if (empresa) {
                url += 'supplier/' + empresa + '/';
            }
            if (incisivo) {
                url += 'incisive/' + incisivo + '/';
            }
            if (modalidade) {
                url += 'modality/' + modalidade + '/';
            }
            if (naturezaDespesa) {
                url += 'natureExpense/' + naturezaDespesa + '/';
            }
            window.location = url;
        }
    });
</script>