<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Edição de CATMAT/CATSER
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>altera/" method="post" id="form">
                            <input type="hidden" name="id" value="<?= $this->view->result['id']; ?>">
                            <div class="row">
                                <div class="col-lg-2">
                                    <div class="form-group">
                                        <label>Tipo</label>
                                        <select name="tipo" id="tipo" class="form-control" required>
                                            <option value="MATERIAL" <?= ($this->view->result['type'] == "MATERIAL") ? 'selected' : "" ?>>
                                                Material
                                            </option>
                                            <option value="SERVICO" <?= ($this->view->result['type'] == "SERVICO") ? 'selected' : "" ?>>
                                                Serviço
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-2">
                                    <div class="form-group">
                                        <label>Situação atual</label>
                                        <select name="sitatual" id="sitatual" class="form-control" required>
                                            <option value="Ativo" <?= ($this->view->result['isActive'] == 1) ? "selected" : "" ?>>Ativo</option>
                                            <option value="Não ativo" <?= ($this->view->result['isActive'] == 1) ? "selected" : "" ?>>Não ativo</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label>Sustentabilidade</label>
                                        <select name="sitsustentavel" id="sitsustentavel" class="form-control" required>
                                            <option value="SUSTENTÁVEL" <?= (($this->view->result['sustainable'] == "SUSTENTÁVEL") ? 'selected' : '') ?>>SUSTENTÁVEL</option>
                                            <option value="NÃO SUSTENTÁVEL" <?= (($this->view->result['sustainable'] == "SUSTENTÁVEL") ? 'selected' : '') ?>>NÃO SUSTENTÁVEL</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-2">
                                    <div class="form-group">
                                        <label>Código do grupo</label>
                                        <input type="text" id="codgrupo" name="codgrupo" placeholder="Código do grupo" class="form-control" value="<?= $this->view->result['group_id']; ?>" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Código da classe</label>
                                        <input type="text" id="codclasse" name="codclasse" placeholder="Código da classe" class="form-control" value="<?= $this->view->result['class_id']; ?>" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Código do PDM</label>
                                        <input type="text" id="codpdm" name="codpdm" placeholder="Código do PDM" class="form-control" value="<?= $this->view->result['pdm_id']; ?>" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Código do item</label>
                                        <input type="text" id="coditem" name="coditem" placeholder="Código do item" class="form-control" value="<?= $this->view->result['item_id']; ?>" required>
                                    </div>

                                </div>
                                <div class="col-lg-10">
                                    <div class="form-group">
                                        <label>Descrição do grupo</label>
                                        <input type="text" id="descgrupo" name="descgrupo" placeholder="Descrição do grupo" class="form-control" value="<?= $this->view->result['group_description']; ?>" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Descrição da classe</label>
                                        <input type="text" id="descclasse" name="descclasse" placeholder="Descrição da classe" class="form-control" value="<?= $this->view->result['class_description']; ?>" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Descrição do PDM</label>
                                        <input type="text" id="descpdm" name="descpdm" placeholder="Descrição do PDM" class="form-control" value="<?= $this->view->result['pdm_description']; ?>" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Descrição do item</label>
                                        <input type="text" id="descitem" name="descitem" placeholder="Descrição do item" class="form-control" value="<?= $this->view->result['item_description']; ?>" required>
                                    </div>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <br>
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Alterar</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                    </div>
                    </form>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->