<?php

use App\Helpers\Pagination;

$pagination = Pagination::make($this);

?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>CATMAT/CATSER</h3>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                <a href="<?= $this->view->controller; ?>novo/" class="btn btn-info">
                    <i class="fa fa-plus"></i> Novo Registro de CATMAT/CATSER
                </a>
                <?php endif ?>
                <br><br>
                <?php if ($this->view->result) : ?>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Tipo</th>
                                <th>Código do grupo</th>
                                <th>Descrição do grupo</th>
                                <th>Código da classe</th>
                                <th>Descrição da classe</th>
                                <th>Código do PDM</th>
                                <th>Descrição do PDM</th>
                                <th>Código do item</th>
                                <th>Descrição do item</th>
                                <th>Situação atual</th>
                                <th>Sustentabilidade</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->view->result as $value) : ?>
                                <tr>
                                    <td><?= $value['type']; ?></td>
                                    <td><?= $value['group_id']; ?></td>
                                    <td><?= $value['group_description']; ?></td>
                                    <td><?= $value['class_id']; ?></td>
                                    <td><?= $value['class_description']; ?></td>
                                    <td><?= $value['pdm_id']; ?></td>
                                    <td><?= $value['pdm_description']; ?></td>
                                    <td><?= $value['item_id']; ?></td>
                                    <td><?= $value['item_description']; ?></td>
                                    <td>
                                        <span class='label label-<?= $value['isActive'] == 1 ? 'success' : 'danger'; ?>'>
                                            <?= $value['isActive'] == 1 ? 'Ativo' : 'Inativo'; ?>
                                        </span>
                                    </td>
                                    <td><?= $value['sustainable']; ?></td>
                                    <td>
                                        <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                                        <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>')" class="btn btn-danger">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                        <?php endif ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>
                <?= $pagination; ?>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->