<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?=$this->view->title?></h5>
                
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Edição de OM
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?=$this->view->controller;?>altera/" method="post" id="form">
                            <input type="hidden" name="id" value="<?=$this->view->result['id'];?>">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Nome</label>
                                    <input type="text"
                                        id="name"
                                        name="name"
                                        placeholder="Nome da OM"
                                        class="form-control"
                                        maxlength="100"
                                        value="<?= $this->view->result['name']; ?>"
                                        required>
                                </div>

                                <div class="form-group">
                                    <label>Indicativo Naval</label>
                                    <input type="text"
                                        id="naval_indicative"
                                        name="naval_indicative"
                                        placeholder="Indicativo Naval da OM"
                                        class="form-control"
                                        maxlength="6"
                                        value="<?= $this->view->result['naval_indicative']; ?>"
                                        required>
                                    <p class="help-block">Ex.: QRTDIS; CITBEL.</p>
                                </div>

                                <div class="form-group">
                                    <label>UASG</label>
                                    <input type="text"
                                        id="uasg"
                                        name="uasg"
                                        placeholder="UASG da OM"
                                        class="form-control"
                                        maxlength="6"
                                        value="<?= $this->view->result['uasg']; ?>"
                                        required>
                                    <p class="help-block">Ex.: 771100.</p>
                                </div>


                                <div class="form-group">
                                    <br>
                                    <button class="btn btn-primary"><i class="fa fa-check"></i> Alterar</button>
                                    <a href="<?=$this->view->controller;?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                </div>
                            </div>
                        </div>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
