<?php

use App\Helpers\Pagination;

$pagination = Pagination::make($this);

?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Naturezas de Despesas</h3>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                <a href="<?= $this->view->controller; ?>novo/" class="btn btn-info">
                    <i class="fa fa-plus"></i> Novo Registro
                </a>
                <?php endif ?>
                <br><br>
                <?php if ($this->view->result) : ?>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Descrição</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->view->result as $value) : ?>
                                <tr>
                                    <td><?= $value['codigo']; ?></td>
                                    <td><?= $value['descricao']; ?></td>
                                    <td>
                                        <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                                        <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success">
                                            <i class="fa fa-edit"></i> Editar
                                        </a>
                                        <a onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>')" class="btn btn-danger">
                                            <i class="fa fa-trash"></i> Eliminar
                                        </a>
                                        <?php endif ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>
                <?= $pagination; ?>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->