            <ul class="nav navbar-top-links navbar-right">
            <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle"
                    href="#"
                    id="userDropdown"
                    role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                        <?= $this->view->userLoggedIn['name'] ?? ''; ?>
                    </span>
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                        <a class="dropdown-item">
                            <i class="fa fa-user fa-fw"></i>
                            <?= $this->view->userLoggedIn['name'] ?? ''; ?>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="acesso/editar/id/<?= $this->view->userLoggedIn['id'] ?? ''; ?>">
                            <i class="fa fa-gear fa-fw"></i>
                            Configurações
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="acesso/logout/">
                            <i class="fa fa-sign-out fa-fw"></i> Sair
                        </a>
                    </div>
                </li>
            </ul>
            <!-- /.navbar-top-links -->