<?php

use App\Helpers\Pagination;
use App\Helpers\View;

$pagination = Pagination::make($this);

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Processos Licitatórios</h3>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                    <a href="<?= $this->view->controller; ?>novo/" class="btn btn-info">
                        <i class="fa fa-plus-circle"></i> Novo Registro
                    </a>
                <?php endif ?>
                <?= $pagination; ?>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Número</th>
                            <th>Modalidade</th>
                            <th>Descrição</th>
                            <th>UASG</th>
                            <th>OM Líder</th>
                            <th>Validade</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value) : ?>
                            <tr>
                                <td><?= $value['number']; ?></td>
                                <td><?= $value['modality_id']; ?></td>
                                <td><?= $value['description']; ?></td>
                                <td><?= $value['uasg']; ?></td>
                                <td><?= $value['oms_id']; ?></td>
                                <td>
                                    <span class="badge badge-danger">
                                        <?= View::humanDate($value['validate']); ?>
                                        <?php if ($value['validate'] < date("Y-m-d")) : ?>
                                            - VENCIDA
                                        <?php endif ?>
                                    </span>
                                </td>
                                <td>
                                    <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                                        <a href="item/novo/idlista/<?= $value['id']; ?>" class="btn btn-info btn-sm">
                                            <i class="fa fa-plus-circle"></i> Add
                                        </a>
                                    <?php endif ?>
                                    <a href="item/listar/idlista/<?= $value['id']; ?>" class="btn btn-primary btn-sm">
                                        <i class="fa fa-list"></i> Itens
                                    </a>
                                    <?php if (in_array($this->view->userLoggedIn['level'], [1])) : ?>
                                        <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>')" class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>